#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: 3d985eb
#
Name     : kimageannotator
Version  : 0.7.1
Release  : 5
URL      : https://github.com/ksnip/kImageAnnotator/archive/v0.7.1/kImageAnnotator-0.7.1.tar.gz
Source0  : https://github.com/ksnip/kImageAnnotator/archive/v0.7.1/kImageAnnotator-0.7.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: kimageannotator-data = %{version}-%{release}
Requires: kimageannotator-lib = %{version}-%{release}
Requires: kimageannotator-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : googletest-dev
BuildRequires : kcolorpicker-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# kImageAnnotator [![Linux Build Status][github-badge-linux]][github-url-linux] [![Windows Build Status][github-badge-windows]][github-url-windows] [![Translation status][weblate-badge]][weblate-url]
Tool for annotating images

%package data
Summary: data components for the kimageannotator package.
Group: Data

%description data
data components for the kimageannotator package.


%package dev
Summary: dev components for the kimageannotator package.
Group: Development
Requires: kimageannotator-lib = %{version}-%{release}
Requires: kimageannotator-data = %{version}-%{release}
Provides: kimageannotator-devel = %{version}-%{release}
Requires: kimageannotator = %{version}-%{release}

%description dev
dev components for the kimageannotator package.


%package lib
Summary: lib components for the kimageannotator package.
Group: Libraries
Requires: kimageannotator-data = %{version}-%{release}
Requires: kimageannotator-license = %{version}-%{release}

%description lib
lib components for the kimageannotator package.


%package license
Summary: license components for the kimageannotator package.
Group: Default

%description license
license components for the kimageannotator package.


%prep
%setup -q -n kImageAnnotator-0.7.1
cd %{_builddir}/kImageAnnotator-0.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710535731
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710535731
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kimageannotator
cp %{_builddir}/kImageAnnotator-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/kimageannotator/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kImageAnnotator/translations/kImageAnnotator_ar.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_bg.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_ca.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_cs.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_da.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_de.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_el.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_es.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_eu.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_fr.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_fr_CA.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_gl.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_hr.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_hu.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_id.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_it.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_ja.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_ko.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_nl.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_no.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_pl.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_pt.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_pt_BR.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_ro.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_ru.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_si.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_sq.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_sv.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_tr.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_uk.qm
/usr/share/kImageAnnotator/translations/kImageAnnotator_zh_CN.qm

%files dev
%defattr(-,root,root,-)
/usr/include/kImageAnnotator-Qt5/kImageAnnotator/KImageAnnotator.h
/usr/include/kImageAnnotator-Qt5/kImageAnnotator/KImageAnnotatorExport.h
/usr/lib64/cmake/kImageAnnotator-Qt5/kImageAnnotator-Qt5Config-version.cmake
/usr/lib64/cmake/kImageAnnotator-Qt5/kImageAnnotator-Qt5Config.cmake
/usr/lib64/cmake/kImageAnnotator-Qt5/kImageAnnotator-targets-relwithdebinfo.cmake
/usr/lib64/cmake/kImageAnnotator-Qt5/kImageAnnotator-targets.cmake
/usr/lib64/libkImageAnnotator.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libkImageAnnotator.so.0.7.1
/usr/lib64/libkImageAnnotator.so.0
/usr/lib64/libkImageAnnotator.so.0.7.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kimageannotator/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
